apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: {{ .Release.Namespace }}
data:
  Corefile: |
    {{ .Values.domain }}:53 {
        log
        template IN A {{ .Values.domain }} {
            answer "{{ "{{" }} .Name {{ "}}" }} 60 IN A {{ .Values.traefikIP }}"
        }
    }
    .:53 {
        forward . 1.1.1.1 8.8.8.8
        log
        cache 30
    }
