apiVersion: v1
kind: Service
metadata:
  name: coredns-custom
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: coredns-custom
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 30053
      protocol: TCP
