apiVersion: v1
kind: Service
metadata:
  name: coredns-custom
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: ""
spec:
  type: LoadBalancer
  selector:
    app: coredns-custom
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
