apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "82.10.1"
    helm:
      values: |
        grafana:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
          admin:
            existingSecret: grafana-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.dc.internal
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki:3100
              access: proxy
              isDefault: false
            - name: Tempo
              type: tempo
              url: http://tempo:3200
              access: proxy
              isDefault: false
        prometheusOperator:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
        prometheus:
          prometheusSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: DoesNotExist
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.dc.internal
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
        alertmanager:
          alertmanagerSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: DoesNotExist
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
