apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-automation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/d0ntay/dc-cluster.git
    targetRevision: main
    path: charts/network-automation
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: network-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
