apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/d0ntay/dc-cluster.git
    targetRevision: HEAD
    path: secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
