apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.gitea.storage }}
