apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nautobot-db-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
