---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBKiS9RYGTtzEew8cgy447wO+Sh18aZ9RFoSi8F/kbSZevv01C09vWntnf5VTHJP7itg6yCiAwOTBN1lDFQsSwUdRtFC9PcT/hhpvFCuMbi/RE3i6y7Chwrb94R/INNdaV6uqORHzW2X457ZcRPgzchsI1piXqXjH8qu8vDrnQ5n7SlJmtavPAwUMTUoD5ivTXO5aYZeEjouKSN09Q1uM7VkVQ3cBEAxkwZO/owQ+n2ASc0sLTIfyvUnla/JrvtJ/cFGcnBdYVSOjm3OFWfUle9e1XeY1zHCe6mG+cUzBVC3ssa7+bF2PokwxkHVvsCQ7jJGmLQOSkWDAdF/IwIPH0Ng9y/1+gFHamHzVIOihlbElPK9y5yUWodnwTSvAM0M0wDIxB5hP2r3mNdP5C78HAvGziCvsE1nk6+o2jUbBgEArW3pIpi/UapxI56VDxBusJ0EMO0lwHCJYI1SHZXCG/5hTN+XCl8DsgG1IgjipLBjAhQ7mNOo5VS6XheKllZ4uiocE+ct3NrzPdykUR2+0OrD3wltvN8jJwrbJmiQ/zHouEPpuAEvLtIc2WHkXp6DQfoJI+PMQnKPGrTHOYCwQVbEt3ZnCCJyqfb634/X14tEEsmGBNsD5HouBDLSt/NIT0m+uaocHkdS2yUwog383R+L4uYKW5y/BofYLxc6eS9nmG3iJ7b65XmnRZ6FJtwF5SMRv8zQbSkO0Hw07I=
    admin-user: AgAPC1g2GLGAM7zJa2KiKz/AO+cW9ZSY50Qvo1/Y/DUvAkrIg66vY+kor+b14pMsQBlFIb8kOddrzNZ23uK8woAiBZ4wiZneHknnudT9XjJaq7o1v73h/tHdIowu90ZP10XFAh7bsYWnH1t6EWhR3p0d+zsjRFHKckL61ryLNf6LGgZsJ2dXk7sbL2qsI+3R7AQdDaXG3AUIMLdMZenKixKpjrnB9rokrM+EY6uOfjM5URVhqaxPJcMeMIkHeEwsfVxW7SkxWAeLkmsF4mQ0M6yrye6MW+tyQwvpGso7CT7aLMI1RC+dVOg8MpvmNEEse6RIVMYFk6YbO2Dui/qBIZ8YaHk7T84G5jK5O24yZz78eHZd9T1t6/QAEMb/uzosL6ugCZBehZTU76VXLiQ2uaa+xmmT1igSTm9bmD5dAuGI12tloAUlnLcRwK89M+LGG1GgoSAEgOt/6rnJRgxmuZY0YsdjMst+JCnzIO+oS1hyPaM6yHT+GkIs6+67KOI/DxJO34YhTfM0iMvikXbXlBQhlrlSxq37U8xe6ZFlj24AiK1U95joIEDwpUgCYD5six9Ioe+FzYvartvaqavk2NY+EvE2TzEmCalewO3hPbjGmHjk3tdIkodsLUyVRpo4/L1I3oa3/hQwAkCMEhgJ+5dXKb1oGJnZimsn8fiJNbUIZE54C0DT1UCMIUdDm5C6SAwrlMxEaw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
