---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAHGrWd26fks8rbxCw0tdNHa2s7j3S+KqWemcm4Rz2EddqhBUTtdqHBXiLSQdzL4Ex6F0e6lqjYa9WI7bsctZ0d8UCNcGXcCFYreU1EsB7FMxjT5nRuSLSZbuWyC8IVOFuoMrtW3rWxKDMMJYzO3V4uqm05f8zUAKksH4j5YWFM8QzxJd6Erz9JxiPzNBrD2EzWMyfur07KZHBXgEJtgES9+HrUMG8TEVkYQcPLuv2LNfReNUJnDJA9EBtahxz0+Yf2So+S5zcRI/ht2ARCpWohIzl0aJsg71PibauzzpOWyzcGnNnPy3LsXesCPMYwI10FsdC2b9inJ0yi2iFt1KmOPTmA0mVy4xHnwrKufQ6zclKUyBV8EKiIN8wZBMjtc4s2T9PRIepO9wlKDNDrZwBZkQE4ZvujidGu4UfNupg4vLavtyNvamvI7YK/sEJNI0yds0pvsZHuj17KjxmxZdyCU8JPc6+cX0ebvR0orXvdEoLg3yymi6zXQdHxC7ICoTaDeon4IGqatl6UwzT74rBg3fpguxVqJQMBvERQKKoDwa3BPpPfFoxDpQJmQrY7HJ9X1RL/kCwTVZeRVgpIfkLU+77hO01EzqtFnnGFvr5UibDcqvzRr8kZYojvp2ctl+ph0n/xdsag98nubEyj0CeaCKxEcQPUdIw4Y4zDmcW8kAA7dQ7+P0fT7r8xQ+5lfNNmT6A4OUVZwXTDn9Ho0RU=
    admin-user: AgBS8BW7ldbR9ujrXsfnizz1eSUVThACeMZSpNHIyCHB1tuZnFfN35BrbvRPQ64qhv0J5NzBC/ivFvtkMNsE0Ub5NKchcv9v21/XCmsxcmLAmXngPuyTbSyXl+G3uP3aeG1XDTeymvzrY4HsuyzP4etmZcGZy/mQ3y7diTEXlH+RJzGbNPf1h+Wo23SvTKkLFFp8cnPrh2BlmmTVxzARKIo+oEJU1fdd0uUajW6heinFQEPpVnWYZoJMaZIhu9pNa+x6DIIearC84UmfG+mbSFMgjG0gG2jRO9g57dRR41IkkebaZvORPANuMGmWX3MLucemxqflQyrcxNIXuktSou2/c4HGvshtyvdZx9Sf+G8lMtu+KQzs3MRiBRRAz4mIy23A931azXgygH/4RCvWiEfJaPhOSBjkg2TwmdVfW+J5seviXUgMOA+QcdeAWcd0MrgPMM19+KaAf0yAuGL+DV7keeeXUJ/bYb4+Z6xNfbkRCah/gwXRBGflc3rQ7k9MCSn8i/1CUX/cHLTm1+nnjvJJ7HFHFH8Bbeamz0B++A+Ix1rJcVKH+l6w8uAn629lCLgcOxPXn5rZHyZCKsm9vKLM7wOWABYqd4N+XnF4uoX8S9c1FxKlNGxhWtq0/JdkRvLj/k1jYJeLGH7Kf9Gi2mptcv3cCZiTkJqMkpqMccKw1AiIkSOdmRiW4qHvw0cQ+4Y0K9mdtuw=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
