---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAcyXhEXnyfXH71Erilephin3JTv5zspOWhc2BY3cqP9zWV132vV3qZggtCV5uKcLNo/7XCtpFg2rNJBxXL306nDQ3qZSYpWicQ+7QV9wBW6kROqkjeRac0T66vpI5s+Nov2VDSmvBEsDihyC7BEzYyBHjDZIimrZp1mVPI1TP3pNs2c8RewlmH1M4PXNKqhQWBVGA+cmK9HX/UqZFCc0CRi6s23tPR0wazv5qd9n7yC1xtpLZPur0fDppHkMPt0A6RJPSOZoZ3dmF14dw/kIV+UM248hR3VL9TZGPr8Zv4S3vb4XxoExW40vRN6pF4HAhgGDqCP4v6IZCEmXRVoAEBzE8dXWEs4rDax8vlocsXQymVn0HTvb+B8NLX3rvXmvpP6uAVU5bWnY7qinoRPCGG3Bh349syL+Y0q9+XnAJfuJG542r5oO3GSy3AqNjrHngs6SyAepxI7Q7mYevx2do+mz6d5+DO9Bi6FucpQ9Gbj6ORIDm/Qf4YT8vlXwrvgC5DiSFQ5WeKGA1ybf4zplFQA3H6Ki/RCXKSSI1Bz7tgcLfnL6VGXEr6a6/F5D1TL97pIwG6z4nAWi3CKh4wF7Ll9BP0tf1ux39Tx5iyRgX0VKuuvhXFbVuikrOAXTXDaf6WOzoQlTulMMrRyzczVlb6sZ7Z+iYhQKdyfdceAakNZcA0/dSIcSzz31jcK2sEyA49zjYKl/SA2Z1giEHlam18/nRBW5c=
    admin-user: AgBgXNUXSribFjEmeQiNs2brc2XOEfSR2YKMvFcGhEkD4aC8/WV0GfGxjz+fs+SxeJfCqXlOkx3QkD6yghWyuv5VFGYvLazT2LVNXZUFkVJTC8oVMgfE/m/RxkNtUYysUAY/Caw5J1dF1oCTnmJxKghmPSOe7FGqDMq+6RSq/LNsaG1kHU7++KLfl3SuKGYo/4N6UPcOnqVFiqKQdjvgmpNHjq6GLo+j8WpSSSeIGlHsWnAsqX8INw2YEAAwratbSqBkw3JCHDfDj8DhCTyAKSMSMwJv9YcMhzMYAYhuCUeg1KzYtDkguMjcQC+qqfm6sFnkbfbbo+X7fxa8DfhpQsTF33eAEzq3FnVB/0z+DhxsXUKFOhIfZAa7sNJXOFcUWqohdoC1K4NhYSSpsN/4bVGlJdL4JaKna4TPZoVkNVV+4zmCGVk5QJ1L5zZxZiJXieLghhGyWDO4vHCZR1w05LYVuupE47O/b10OFNlvrMsmgOHaJduWqSPHIE9siyVYDDaopuXLkQ3QqT6yoRvpD5HxgGIpWvG5zwGLvPQDANoi1d0751rgNF0oame0RBSfM94HE0jJY+BzxGwnk3kTJqeJCCJhQvHxKMbA+qxXpggCwaBKWh6SRWrb7NtAJQ2F4fSj7oCrrhfrmHqefG/RVjdI9F21FOrUOlatD+VmcM7xiWTk9uYvbT9I0ku1eFNQsn37OMgo7A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
