---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBoXWl6u2/TbJlGX0Nzxwv6Hn0lnxeMv4z0/8YWW9RoUBtOWTe0MwCvtNguZmQukV0BhhnxUCvYQsaBwMYjTJIpvUDxHSgVl5ggSe6BzI9ApMity6hG3D7GxIDsHrFdosc3L1Dk/gBLWBMpelokiK+roZx+DkjxLgJiAGBXjZYOQQOaXWHpRGknifRyiNZMs1g0is2lcxTZ6E6a+JSvSWn5leuCN8rTs0XQqQO9b2uTQU1PuRQk4CnGyOBDPwcwJut3dUultoZdza+dZF3WEw8HXrwpnuqCzMvAi+fwv+Mk/1mHOuQ7kyKveW5Nyv/p7qfNWyTABQ9MX3fR4DmZjxhF1AdZAWKMQHvimbEEAqSwUElrRkkNHnThFHpratfDUYO8+NAdQcLAlkE6TsZ9gkF2FIQSsvj8AoYGVAxZuGFjU35ge1mzSFqs8Y6ys3JjBz4x2vLCUKMcxueuYaR/JcSApJP0zyI4fUL/BerlfALZCFridKL6bLMlieK5NKeH0TtpylgiT9V8MbpdhxeEcLSe+oIUghnKI/4cJbJs9aWfHMKrr4pb/Lw2LeeutvhIS2RpAJn9Uc1IaDp8YPFV5tG5gOGAn0ZpT3D5P5Nw9KpMN2CYramo64dM7Q7+mMj0dWTEBmyK7UwikaZtfsNglsZNqGUKLTjwFOltRh+ri6Vo8XIGa0+OThpN/LA6tzXcQemklPvKB0/FU6O3nJs=
  template:
    metadata:
      name: harbor-admin
      namespace: harbor
