---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgA3EdhNanTgioFntZrPKj/GM7XgySGP0JudmvX/oHeRsqiPshTNMVLhl5OE+h7hbiQmKSPLzBMcZsxm/e2ddIol21XhTv6s/tqi9uz2IhmNVW1EOuhn+JuPgSDJSJL7wZv2G7OMTxx8v/VlkMsqJDbH1So0yHmC6Qih8sKHH2fv+DF9BRXKoKMguFycxrZ+ZJG59TpQcXWQRnza1ZCRugXoH79Rp5qTTyNiSL4cArnPafx/RhEH8xM3/sxOVeTfNCh/lqNQv7qlZYWmOK2i5qPfWBk91y0PIPkK/W12jjGdjWP0gdvyJ5xcYj1Q3oznAjYc8DaBKBfRIE83jz/Cx4v36RZAZEmaqAUAO3cbbycx6LVjAzWZu9JuTfWnCUQI80xRJjPSckPa6B1hsLQ1+Rm5GNEYhtvptVOlCdrSm1zcY749NpadH84sjAnDv9PQl4W3jzojGKVaexLdYjYJz7NDNiWPth2p0XPpk9C84wc7TsURRmJa/7gqtLnsTCm7O+QPHaF4VHwD2jegBz6lDTur1IKX3szC01jVOrsRiHBuwz8UcV5aj0lDryx5pcYHquuX+7Iy8h574dPyamEDUkPOTk8xrRSWcOImsNZuhsJcXf+wMlkXCv6d0xDvOrWqqJ+opdPCWI6gd/qPcxk32LMupCOsT32hrkpPGrsUae6rejAFhsOb6Hp0imvvXundrO+cLky0ZvbRq+AjPpo=
    rootUser: AgB0gCOt4QFJnTKaPOEuC9Yv+YYp3JRY+2aBHwavivixLuYF/Jq/daRkZ9nOTl1wpqmGPYoKvcQvlzSTmUqfSX5g1icbSA1p3VQtCf5zmJt3W+StEabkK4KW7Nkns8Sc43gZBVmdOlmdH1vuCgBQWvGoG+WkdjEs0cxCTL0a1X+Qdoh7T/fVbS3U14SPYNkdtf/tLcCnAoaOAKChtULEEKKAnjEm02SAMiVLv/dKoh9Hb3CbyuZzNjXswT0BX+TnUIFSYmBV4eKheE43qWXQswvAfdCX/sT2M9lVF4hZGYO3IiltwHqp7ACgjfdUCPEt3PuxZF5Z6yHVi5C7EbZ9CWd1TmP/1smI2LF5exeSLEIisDg19NMB0UeXuzVEQxFuPobfXljCrAghwEaOmsQQnNkjsKdOGbjKgYzc+g1VS4ZLOWBUxgK0oL96uYCbd5/rleXJZamf1fOEtbX5IpOjWcwy1nv6lSfBd82O2XyvSNaAXSyOlHfAmSJH0sauKD/a+vMnH4Z9dFoaL+vIc9dmUxX+AE7CexqaiCzI1q0MURQQLnu1I2C5pjzUjLfm1vTZI4qwHBcXEalObLc3LmZ12PohGKREd0A6Bnrzs7M75VzAG050o9NCBa2SazP1VoqN+/EuaGGGH1a+o14+Jn4+c4ReNhuQHzVdodmw+nw3rmbWtLEkyfyM5CWHnXGY4ZObYkxJtke2Hw==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
