---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBtcETchWAboCBfVw4JytQUMvXueRs8no3nrPVgquVkAkLTlNxqeiAkmI/6m9e95tOLbcuHmQx5YJ7vFLqP2wqGD5JC2Alfr+pDR8fkDrb3iw2pI304cXrq6GwTZZ0X6NjsAHyDpXotbF+F3MS3IXLd3LTXdbLEO7HBmnFfLrg53L9q5bYUEJzD13v1C0z+P+/cBAvEfXga/ebqhK+6TeET9mINZo+jClttaiAVZ3e6FRqG4vAR1o1iZLye5UFx5/X2wwyf0mK5Iw/Fq9peXcjVxD/bQADRPep84vqLR/dReL9W6lhiKpBKWAekaze5MdrO95EaNck8ulgDOz7VRAMzp8zvDiWwr4ZMruhv8nyMri0dp7HCU1iCtsdO1g55Jgk5CLAM0ptKmCmNlqVQ8697Hnr79aSxrhix6F3bO+sag58Em6ujccM7RtSE5pL70h9pkDRI7pINFN3mApKGNx8dH4TcUAkKde7WvS2cgCjgcgFheWvckdBiCHHxjlz3scxRGAl3+XfBawix0XiEjfpyq5Xdn3JJlTZsxMtKgbdVLmq1F9D6gG6zWgdjTrX9TmZ8NzNH/6Muje3oVs38qvo5BNvknCNPvAeDHGD/ibq1BHwtmtZvrbsC0zcnDMSGTmfY8jgerKXUwxAul3dpfsGHJkLNHZt8ugRsDWFjvNUzqttbD8uZ9ejG7rQ1k4wm3LArJdqHlP7PHuooUj/wvCgVrfkRmluRS5/2s0CnbcBgTw==
    rootUser: AgAIw2Z45ompyFxMm8KVVhATNtNpSM84ZJkJbY0b2QPJWBWHP9t70Xx83IgX1PtBiq7d2NWYIBXoQIfnLbyZ1cE3aHzZAzdmavDFbZTN3aJk7SfHm4hYS2Ltjga1VtnC1/XECeUOjPtl4AHt2UjFEeQ3Wu09OBJtVT0f5tpoX9X3tNojmhU4O3biH9M9OlJCL3LHcPs3G0rm5krAKzWJN3bgxB7oBDZV3D1bzz5Z36neuSmVRTSaAxxHcN2ZUZ7GOrq91akVSQcf2PVOHMxOBEJWPRxKWi294kzPTuklafx4DHbjL7VjjLsD/5000XYBAlmA/RK6LBbVO4P8UpVIpGrJdxl3LBt4uHSag/cWW85gFszo2pjdIVlYCTEmZNTVyYCRxpm5lzRwpevHOpaDdI+TQf+ybRAZYI8XG+2F4qhGU0g5YPHtZIlOdNgbgLw7VNKgk1sAE3Ryp0W7R0ksPzK/a63/BEam4FAb7sD8NDfw+iTU2u1lMMCVdySwNVibdgyGfXkJXMf51Vj60yKr1f9Lotwj/p1AFtCedLZNvyPSVr9C0e4/qlAFJQIaTLHlXKBNJ6vaag/D4xUPUGaDvw+TydHivaLMG8+Y1teuDRKEw3CASwvKfiC2yegusT2cw3Yne6mewqTzcc9qazwp7NJGf69ZN0Pq7BfgAbgV/s+IOBXFi3kEcHvFm7ZtftHnigwK41DoAA==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
