---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgCkUNg5EcLfEYPBo/VbaKmKe/qWYGa9Aa7iv2GA9tA4qnTtE1hxPrE1bRWSRE4PxuuWAw8YY1eg1zo9zbJciWbHNY13JFqCCrReAa2GSMG7/FsHR0tpO3apLEm+cDySaFtQ9AnM0t8jysOMIafGQvWdVvRhbfCshkhoGgr4WyuhS+NfxWggBvR9E11d0RsTRveKYvSjILYn/hlw3jHdqbiqUsAVZgLusDUuPOnJrvGCYR0ELmJvPmB5H1D5KKajQb79jvJXdbt0QDfE2PEuPcLj6/i0E55aY4u0QWPOA/kxzrlREnNeICH7zBqE5Tx51G8EuoUthpElqBfpL2pFPe5kVYaR7g49M+qCfs7EXyzzrlmMtE2ddsh3bo9V4dEI57ADyxkjxc1qfOEgy5fYBxcyo6JqhxD7AAzV9mrHgypx/Uh56tGEV7TNhCMr8kcZCPeDGVZJmYh2bU5/Bw9+NNONwPtoza4Ysu9HEpPZcTkdLwea5iAQ0ZFZbaPoUQR6DoIRRCah0vLzFpvwFkm9EO43Hw73RlA7++sW5lpKNTT2Fp3AiMuwnAqhsOCtqsVVVz1U0VP278C8D5Xk7Lm7afBluaaEha1U37wTFQZMx1XLIJaCN73TYEtmPW87xmap/f6r09xHp0UUaHL4WlAjBirhtfnjbzDNQA6MdcmWUqldy9n8JwdlXp5FI8zPHwfNt/GFPczJB+vGK2I1L6nrF3uzvI7wbdI=
    rootUser: AgAzt5UEZfAGIu0NnQ6Mxg2HOlZFgssLnymJ0Eb/mR2ZfBErrdMIWlJ4fvi/zUtLUUz66ktAJdPe5NUeqtUcoNznGwBMs8Sg9AxyY1qnEX1ndCJl5PyiBG/3LdtgRAgEtiqh+vBZU1nCyY/eI75N5U9ChN/wdoMGWHzvFbTUdzMvoH15lPC90+vVqpIQhfpsrj9/aebNoi5FzGtc3b1rO0YOLsNyU4UZ7NHd4ggyeJDjeu4k18SKgrWzvmUdftcxvCpXwzHup/KIPpbWhYEpz5OWuvw9/acbrfpNGycPsU3urO04q9bLf5q0Epj1F/Peh+HI4l0DrqvdS8Lc7ETsAT26GPMmYmwifmGBZbgpEexamWRC14ft+fwNzM/DMPMNUQbflcV8LYM/ojUoFCAS/gKwlN1IJ0x032NeEd3SRq+p71fSdNaE6BzbfDCuWHZskLM86Fu9PC8FEf0jCW8xUh9mfn0eoYbUH1KaUlVGnqen+gs4gSVi1sJz15v44E6DwM1JK5Lq7DXMwhIZ4+7sBlc4nkcoiG80KIZR2GWeoTrBnpQmf+xo3jD1tGqLJcOQ/LzysXYqwKzahMv3L7LL6yLDqWgnjfBip1y+Ue2CwgLjf5O8JITVXgFk1iJ+qCw8xAZ/sveJqOZL9asolY17rpevta1111xy2f9XMoVf5TfpExhltFoLem/LUVUAc7IxmxqwU+jtNQ==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
