---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: network-automation
spec:
  encryptedData:
    .dockerconfigjson: AgCoVFaOJn5yE82XNzc8prM0i1k32Zwqu1yT7VRfX52o6EPkrcidE7Ura5nlFiDD8U88y0dE8mThJ+jlBQ6KsYEhjModNyyU24ne7Hp23P9BfCMV9ejAdnkFr2qpS6qxHjvExwexT8d+DUuFH/EVpVHo/QHYUZQxEL6aXdOELM0dHj6/J7eh5MOh/1rcOxStDyCc+yuqd9mLX3mOJIEnIykdFLkeOnl5i/NFH7Q/18jzWWfPL6400b8gXE78wDWS+ukt22kINPGBdltEjaC96yTEJwZ+A3ilXs07xZq06r1QVBkSLbG/Wn8IT/Bpy88iiq3Do2qBFwf3P6WkqZinx8ojU2JCR0YK5JSR1XUt/zOwn0b6yZ4E+h0zNErZclLuy0v5OJHwGKfJoIp6eWz8i9lXWzIB7WEOvfOZI9LGfqthCHKKxm6oRWXQj4IIvAJXZgBSdS0W3b/l1qNPSNEWrjJ+IGGc2Jv03C+6Xw5RUCqX8kaKyn7VQ00r800wvAiMXtnWeZloOC/suKTit/XoyPWjm++oBgN/U0YFAHowAW/BGbKB5zk8fUil9yhUs3DRu8Cco8Wy/gbuBL2OXDTtF+oMU1g2GKbZqt/Vh3ns4VJFJTts6iyB+eGS2+gwc0A05YpxP8BUuuQV5lbUDBGMGeP62bT/to/tE2kS9Zx/rj8wGx3YT8ay45iYDLtGlCmbGA+G8cvjFyWeGs7zwaO7SV5y67Ff0ow969E5jOCIXk4SoSieXw2oPmN1LzKFakjE5DwhmRxMvtKp39M/UqTHowUQkctcgmxHoZm74XkQHWlRS7scRLgc1mYmURIgSzHiEHy3/C/fAT0m9VkQBiWLg29mHw==
  template:
    metadata:
      name: harbor-pull-secret
      namespace: network-automation
    type: kubernetes.io/dockerconfigjson
